### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jalone87** [justinshapiro/SetlistFmKit#1]
Hi, great job, would you mind adding a license to this project, so that it can be used, enhanced or forked in projects and i may add some pull requests? 
Thanks a lot

**Comment by justinshapiro** [comment]
@jalone87 Thanks for raising this. I added an MIT license to the repo. Since it's been quite a few years since I initially published this, I also updated it to use Swift Package Manager as before it was just using framework targets.

**Comment by jalone87** [comment]
Thanks so much! Exactly what i needed
